"""empty message

Revision ID: 01626890d503
Revises: b2651f391adf
Create Date: 2020-11-06 14:32:48.312113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01626890d503'
down_revision = 'b2651f391adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblpricelist', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpricelist', sa.Column('description', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
