"""empty message

Revision ID: 1198e46086f1
Revises: 89e56c1f700e
Create Date: 2020-11-24 10:13:21.103278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1198e46086f1'
down_revision = '89e56c1f700e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblitems', sa.Column('barcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblitems', 'barcode')
    # ### end Alembic commands ###
