"""empty message

Revision ID: 16084d545d98
Revises: 3d9e4460aed8
Create Date: 2020-11-12 08:57:22.533393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16084d545d98'
down_revision = '3d9e4460aed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblsales', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tblsales', sa.Column('longtitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblsales', 'longtitude')
    op.drop_column('tblsales', 'latitude')
    # ### end Alembic commands ###
