"""empty message

Revision ID: 21830c5b874c
Revises: fae78f8156e6
Create Date: 2020-11-13 10:50:43.677745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21830c5b874c'
down_revision = 'fae78f8156e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblitemadjoutrow', sa.Column('whsecode', sa.String(length=100), nullable=False))
    op.drop_constraint('FK__tblitemadj__whse__009508B4', 'tblitemadjoutrow', type_='foreignkey')
    op.create_foreign_key(None, 'tblitemadjoutrow', 'tblwhses', ['whsecode'], ['whsecode'])
    op.drop_column('tblitemadjoutrow', 'whse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblitemadjoutrow', sa.Column('whse', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblitemadjoutrow', type_='foreignkey')
    op.create_foreign_key('FK__tblitemadj__whse__009508B4', 'tblitemadjoutrow', 'tblwhses', ['whse'], ['whsecode'])
    op.drop_column('tblitemadjoutrow', 'whsecode')
    # ### end Alembic commands ###
