"""empty message

Revision ID: 262c56c23667
Revises: 9cb00470b59c
Create Date: 2020-11-06 08:14:25.754588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262c56c23667'
down_revision = '9cb00470b59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpaymentrow', sa.Column('reference2', sa.String(length=100), nullable=True))
    op.add_column('tblpaymentrow', sa.Column('sap_number', sa.Integer(), nullable=True))
    op.drop_column('tblpaymentrow', 'reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpaymentrow', sa.Column('reference', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('tblpaymentrow', 'sap_number')
    op.drop_column('tblpaymentrow', 'reference2')
    # ### end Alembic commands ###
