"""empty message

Revision ID: 3d9e4460aed8
Revises: 7bcfe4db21f1
Create Date: 2020-11-11 17:29:46.884170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '3d9e4460aed8'
down_revision = '7bcfe4db21f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblwhses', 'sales',
               existing_type=mssql.BIT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblwhses', 'sales',
               existing_type=mssql.BIT(),
               nullable=False)
    # ### end Alembic commands ###
