"""empty message

Revision ID: 40f81e25e885
Revises: 86d3cf4408ab
Create Date: 2020-11-07 08:58:02.535007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f81e25e885'
down_revision = '86d3cf4408ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK__tblpricel__item___3E923B2D', 'tblpricelistrow', type_='foreignkey')
    op.drop_column('tblpricelistrow', 'item_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpricelistrow', sa.Column('item_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('FK__tblpricel__item___3E923B2D', 'tblpricelistrow', 'tblitems', ['item_code'], ['id'])
    # ### end Alembic commands ###
