"""empty message

Revision ID: 421d1780c87c
Revises: b65229475542
Create Date: 2020-11-05 10:39:38.043838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421d1780c87c'
down_revision = 'b65229475542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbldeposit', sa.Column('sap_number', sa.Integer(), nullable=True))
    op.add_column('tblpayment', sa.Column('sap_number', sa.Integer(), nullable=True))
    op.drop_column('tblpayment', 'ap_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpayment', sa.Column('ap_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tblpayment', 'sap_number')
    op.drop_column('tbldeposit', 'sap_number')
    # ### end Alembic commands ###
