"""empty message

Revision ID: 52868edd16fd
Revises: a23f7ef828e3
Create Date: 2020-11-20 10:46:49.569677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52868edd16fd'
down_revision = 'a23f7ef828e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblpulloutreqrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulloutreq_id', sa.Integer(), nullable=False),
    sa.Column('whsecode', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('objtype', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['tblitems.item_code'], ),
    sa.ForeignKeyConstraint(['pulloutreq_id'], ['tblpulloutreq.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['tbluom.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['whsecode'], ['tblwhses.whsecode'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tblpulloutrowreq')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblpulloutrowreq',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, mssql_identity_start=1, mssql_identity_increment=1),
    sa.Column('pulloutreq_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('whsecode', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('objtype', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('uom', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP850_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('date_updated', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['tbluser.id'], name='FK__tblpullou__creat__1CFC3D38'),
    sa.ForeignKeyConstraint(['item_code'], ['tblitems.item_code'], name='FK__tblpullou__item___1DF06171'),
    sa.ForeignKeyConstraint(['pulloutreq_id'], ['tblpulloutreq.id'], name='FK__tblpullou__pullo__1EE485AA'),
    sa.ForeignKeyConstraint(['uom'], ['tbluom.code'], name='FK__tblpulloutr__uom__1FD8A9E3'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbluser.id'], name='FK__tblpullou__updat__20CCCE1C'),
    sa.ForeignKeyConstraint(['whsecode'], ['tblwhses.whsecode'], name='FK__tblpullou__whsec__21C0F255'),
    sa.PrimaryKeyConstraint('id', name='PK__tblpullo__3213E83F2319F364')
    )
    op.drop_table('tblpulloutreqrow')
    # ### end Alembic commands ###
