"""empty message

Revision ID: 6bbfea07c75b
Revises: dc110a062ab0
Create Date: 2020-11-19 10:12:51.958097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbfea07c75b'
down_revision = 'dc110a062ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblfinalcount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('seriescode', sa.String(length=50), nullable=False),
    sa.Column('transnumber', sa.Integer(), nullable=False),
    sa.Column('objtype', sa.Integer(), nullable=False),
    sa.Column('transdate', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=250), nullable=True),
    sa.Column('docstatus', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['objtype'], ['tblobjtype.objtype'], ),
    sa.ForeignKeyConstraint(['series'], ['tblseries.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblfinalcountrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finalcount_id', sa.Integer(), nullable=False),
    sa.Column('whsecode', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('sales_count', sa.Float(), nullable=False),
    sa.Column('auditor_count', sa.Float(), nullable=False),
    sa.Column('manager_count', sa.Float(), nullable=False),
    sa.Column('final_count', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['finalcount_id'], ['tblfinalcount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_code'], ['tblitems.item_code'], ),
    sa.ForeignKeyConstraint(['uom'], ['tbluom.code'], ),
    sa.ForeignKeyConstraint(['whsecode'], ['tblwhses.whsecode'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblfinalcountrow')
    op.drop_table('tblfinalcount')
    # ### end Alembic commands ###
