"""empty message

Revision ID: 7bcfe4db21f1
Revises: 2ec1bca57907
Create Date: 2020-11-07 14:38:11.558231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcfe4db21f1'
down_revision = '2ec1bca57907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblwhses', sa.Column('pricelist', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tblwhses', 'tblpricelist', ['pricelist'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblwhses', type_='foreignkey')
    op.drop_column('tblwhses', 'pricelist')
    # ### end Alembic commands ###
