"""empty message

Revision ID: 86d3cf4408ab
Revises: f2c96a616117
Create Date: 2020-11-06 16:28:06.426655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d3cf4408ab'
down_revision = 'f2c96a616117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('isCanAddSap', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbluser', 'isCanAddSap')
    # ### end Alembic commands ###
