"""empty message

Revision ID: 89e56c1f700e
Revises: e90627e44570
Create Date: 2020-11-23 11:55:30.486447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e56c1f700e'
down_revision = 'e90627e44570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblitemreq', sa.Column('sap_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblitemreq', 'sap_number')
    # ### end Alembic commands ###
