"""empty message

Revision ID: 9cb00470b59c
Revises: 421d1780c87c
Create Date: 2020-11-05 10:44:22.775020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb00470b59c'
down_revision = '421d1780c87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('agent_sales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('ar_sales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('cash_sales', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbluser', 'cash_sales')
    op.drop_column('tbluser', 'ar_sales')
    op.drop_column('tbluser', 'agent_sales')
    # ### end Alembic commands ###
