"""empty message

Revision ID: a23f7ef828e3
Revises: 6bbfea07c75b
Create Date: 2020-11-20 10:08:55.335558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23f7ef828e3'
down_revision = '6bbfea07c75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblfinalcountrow', sa.Column('ending_auditor_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('ending_final_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('ending_manager_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('ending_sales_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('po_auditor_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('po_final_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('po_manager_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('po_sales_count', sa.Float(), nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('variance', sa.Float(), nullable=False))
    op.drop_column('tblfinalcountrow', 'final_count')
    op.drop_column('tblfinalcountrow', 'auditor_count')
    op.drop_column('tblfinalcountrow', 'manager_count')
    op.drop_column('tblfinalcountrow', 'sales_count')
    op.add_column('tblpulloutrow', sa.Column('to_whse', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'tblpulloutrow', 'tblwhses', ['to_whse'], ['whsecode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblpulloutrow', type_='foreignkey')
    op.drop_column('tblpulloutrow', 'to_whse')
    op.add_column('tblfinalcountrow', sa.Column('sales_count', sa.FLOAT(precision=53), autoincrement=False, nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('manager_count', sa.FLOAT(precision=53), autoincrement=False, nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('auditor_count', sa.FLOAT(precision=53), autoincrement=False, nullable=False))
    op.add_column('tblfinalcountrow', sa.Column('final_count', sa.FLOAT(precision=53), autoincrement=False, nullable=False))
    op.drop_column('tblfinalcountrow', 'variance')
    op.drop_column('tblfinalcountrow', 'po_sales_count')
    op.drop_column('tblfinalcountrow', 'po_manager_count')
    op.drop_column('tblfinalcountrow', 'po_final_count')
    op.drop_column('tblfinalcountrow', 'po_auditor_count')
    op.drop_column('tblfinalcountrow', 'ending_sales_count')
    op.drop_column('tblfinalcountrow', 'ending_manager_count')
    op.drop_column('tblfinalcountrow', 'ending_final_count')
    op.drop_column('tblfinalcountrow', 'ending_auditor_count')
    # ### end Alembic commands ###
