"""empty message

Revision ID: ac0fa831685d
Revises: a04b2ac81210
Create Date: 2020-11-16 09:03:30.575786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0fa831685d'
down_revision = 'a04b2ac81210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblpulloutreq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('seriescode', sa.String(length=50), nullable=False),
    sa.Column('transnumber', sa.Integer(), nullable=False),
    sa.Column('objtype', sa.Integer(), nullable=False),
    sa.Column('transdate', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=250), nullable=True),
    sa.Column('docstatus', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['objtype'], ['tblobjtype.objtype'], ),
    sa.ForeignKeyConstraint(['series'], ['tblseries.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['updated_by'], ['tbluser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tblpulloutrowreq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulloutreq_id', sa.Integer(), nullable=False),
    sa.Column('whsecode', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('objtype', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['tblitems.item_code'], ),
    sa.ForeignKeyConstraint(['pulloutreq_id'], ['tblpulloutreq.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom'], ['tbluom.code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbluser.id'], ),
    sa.ForeignKeyConstraint(['whsecode'], ['tblwhses.whsecode'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblpulloutrowreq')
    op.drop_table('tblpulloutreq')
    # ### end Alembic commands ###
