"""empty message

Revision ID: b4676b756a49
Revises: 01626890d503
Create Date: 2020-11-06 14:35:25.514892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4676b756a49'
down_revision = '01626890d503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblpricelist', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblpricelist', 'description')
    # ### end Alembic commands ###
