"""empty message

Revision ID: b65229475542
Revises: bb207eeb09a1
Create Date: 2020-11-05 08:18:44.026731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65229475542'
down_revision = 'bb207eeb09a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblcustomer', sa.Column('dep_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblcustomer', 'dep_balance')
    # ### end Alembic commands ###
