"""empty message

Revision ID: b8ac984bb77d
Revises: 68d12179f67e
Create Date: 2020-11-06 15:46:58.826035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b8ac984bb77d'
down_revision = '68d12179f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('isARSales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isAgentSales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isAuditor', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isCanAddSAP', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isCashSales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isCashier', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isDiscount', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isManager', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isReceive', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isSales', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isTransfer', sa.Boolean(), nullable=True))
    op.add_column('tbluser', sa.Column('isVoid', sa.Boolean(), nullable=True))
    op.drop_column('tbluser', 'agent_sales')
    op.drop_column('tbluser', 'cashier')
    op.drop_column('tbluser', 'auditor')
    op.drop_column('tbluser', 'ar_sales')
    op.drop_column('tbluser', 'manager')
    op.drop_column('tbluser', 'receive')
    op.drop_column('tbluser', 'transfer')
    op.drop_column('tbluser', 'void')
    op.drop_column('tbluser', 'admin')
    op.drop_column('tbluser', 'active')
    op.drop_column('tbluser', 'discount')
    op.drop_column('tbluser', 'cash_sales')
    op.drop_column('tbluser', 'sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('sales', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('cash_sales', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('discount', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('active', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('admin', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('void', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('transfer', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('receive', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('manager', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('ar_sales', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('auditor', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('cashier', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('tbluser', sa.Column('agent_sales', mssql.BIT(), autoincrement=False, nullable=True))
    op.drop_column('tbluser', 'isVoid')
    op.drop_column('tbluser', 'isTransfer')
    op.drop_column('tbluser', 'isSales')
    op.drop_column('tbluser', 'isReceive')
    op.drop_column('tbluser', 'isManager')
    op.drop_column('tbluser', 'isDiscount')
    op.drop_column('tbluser', 'isCashier')
    op.drop_column('tbluser', 'isCashSales')
    op.drop_column('tbluser', 'isCanAddSAP')
    op.drop_column('tbluser', 'isAuditor')
    op.drop_column('tbluser', 'isAgentSales')
    op.drop_column('tbluser', 'isAdmin')
    op.drop_column('tbluser', 'isActive')
    op.drop_column('tbluser', 'isARSales')
    # ### end Alembic commands ###
