"""empty message

Revision ID: bed8bad98569
Revises: dc41269cd754
Create Date: 2020-11-12 16:16:31.025262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed8bad98569'
down_revision = 'dc41269cd754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblcounting_inv', sa.Column('user_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblcounting_inv', 'user_type')
    # ### end Alembic commands ###
