"""empty message

Revision ID: d10e847d1ba3
Revises: 262c56c23667
Create Date: 2020-11-06 08:26:13.895003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10e847d1ba3'
down_revision = '262c56c23667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbldeposit', sa.Column('reference2', sa.String(length=100), nullable=True))
    op.alter_column('tbldeposit', 'reference',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbldeposit', 'reference',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP850_CI_AS'),
               nullable=True)
    op.drop_column('tbldeposit', 'reference2')
    # ### end Alembic commands ###
