"""empty message

Revision ID: dc41269cd754
Revises: 679990ae1b56
Create Date: 2020-11-12 13:50:46.010276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc41269cd754'
down_revision = '679990ae1b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblcounting_inv', sa.Column('confirm', sa.Boolean(), nullable=True))
    op.add_column('tblcounting_inv', sa.Column('objtype', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tblcounting_inv', 'tblobjtype', ['objtype'], ['objtype'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblcounting_inv', type_='foreignkey')
    op.drop_column('tblcounting_inv', 'objtype')
    op.drop_column('tblcounting_inv', 'confirm')
    # ### end Alembic commands ###
