"""empty message

Revision ID: f2c96a616117
Revises: b8ac984bb77d
Create Date: 2020-11-06 16:26:06.417932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f2c96a616117'
down_revision = 'b8ac984bb77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tbluser', sa.Column('isCanAddSap', sa.Boolean(), nullable=True))
    op.drop_column('tbluser', 'isCanAddSap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbluser', sa.Column('isCanAddSap', mssql.BIT(), autoincrement=False, nullable=True))
    op.drop_column('tbluser', 'isCanAddSap')
    # ### end Alembic commands ###
